version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: abc
      POSTGRES_USER: bookstore
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  bookstore:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - elasticsearch
    environment:
      DB_URL: jdbc:postgresql://bookstore:abc@postgres:5432/bookstore
    ports:
      - "8080:8080"

volumes:
  data01:
    driver: local
